# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json
backend:
  name: github
  repo: traitor-town/wiki
  branch: main

media_folder: public/img
public_folder: /img

collections:
  - name: "maps"
    label: "Maps"
    folder: "maps"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Authors", name: "authors", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
